import { useState } from "react";
import type { LessonPlan } from "@ai-teacher/shared";
import "./App.css";

function App() {
  const [grade, setGrade] = useState<string>("");
  const [subject, setSubject] = useState<string>("");
  const [topic, setTopic] = useState<string>("");
  const [objective, setObjective] = useState<string>("");

  const [lessonPlan, setLessonPlan] = useState<LessonPlan | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>("");

  async function handleSubmit(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();

    setLoading(true);
    setError("");
    setLessonPlan(null);

    try {
      const response = await fetch(
        `${import.meta.env.VITE_API_URL}/api/lessons/generate`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            grade: Number(grade),
            subject,
            topic,
            objective,
          }),
        },
      );

      if (!response.ok) {
        throw new Error("Failed to generate lesson.");
      }

      const data: LessonPlan = await response.json();
      setLessonPlan(data);
    } catch (err) {
      setError(
        "Unable to generate the lesson. Make sure the backend is running.",
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="app">
      <header>
        <h1>AI Classroom Assistant</h1>
        <p>Generate a structured lesson plan from a few simple inputs.</p>
      </header>

      <section className="form-section">
        <form onSubmit={handleSubmit}>
          <label>
            Grade
            <input
              type="number"
              min="1"
              max="12"
              value={grade}
              onChange={(event) => setGrade(event.target.value)}
              placeholder="5"
              required
            />
          </label>

          <label>
            Subject
            <input
              type="text"
              value={subject}
              onChange={(event) => setSubject(event.target.value)}
              placeholder="Science"
              required
            />
          </label>

          <label>
            Topic
            <input
              type="text"
              value={topic}
              onChange={(event) => setTopic(event.target.value)}
              placeholder="The Water Cycle"
              required
            />
          </label>

          <label>
            Learning Goal
            <textarea
              value={objective}
              onChange={(event) => setObjective(event.target.value)}
              placeholder="Students will be able to explain the main stages of the water cycle."
              required
            />
          </label>

          <button type="submit" disabled={loading}>
            {loading ? "Generating..." : "Generate Lesson"}
          </button>
        </form>
      </section>

      {error && <p className="error">{error}</p>}

      {lessonPlan && (
        <section className="lesson">
          <h2>{lessonPlan.lessonTitle}</h2>

          <p>
            <strong>Grade:</strong> {lessonPlan.grade}
          </p>

          <p>
            <strong>Subject:</strong> {lessonPlan.subject}
          </p>

          <p>
            <strong>Topic:</strong> {lessonPlan.topic}
          </p>

          <h3>Learning Goal</h3>
          <p>{lessonPlan.objective}</p>

          <h3>Activity</h3>
          <p>{lessonPlan.activity}</p>

          <h3>Discussion Questions</h3>
          <ul>
            {lessonPlan.discussionQuestions.map((question) => (
              <li key={question}>{question}</li>
            ))}
          </ul>

          <h3>Differentiation</h3>
          <p>
            <strong>Support:</strong> {lessonPlan.differentiation.support}
          </p>
          <p>
            <strong>Extension:</strong> {lessonPlan.differentiation.extension}
          </p>

          <h3>Assessment</h3>
          <p>{lessonPlan.assessment}</p>

          <small>Generated by: {lessonPlan.generatedBy}</small>
        </section>
      )}
    </main>
  );
}

export default App;
