import type { LessonPlan } from "@ai-teacher/shared";
import { saveLessonPlan } from "../api/lessonApi";
import { useState } from 'react'
type LessonPlanDisplayProps = {
  lessonPlan: LessonPlan;
  setError: (message: string) => void
};

export default function LessonPlanDisplay({
  lessonPlan, setError
}: LessonPlanDisplayProps) {
  const [saved, setSaved] = useState<boolean>(false);
  const [saving, setSaving] = useState<boolean>(false);


  async function handleSave() {

    setSaving(true)
    try {
      await saveLessonPlan(lessonPlan);
      setSaved(true)
      alert("Lesson plan saved")
    } catch (error) {
      setError(`Unable to save the lesson. ${error}`)
    } finally {
      setSaving(false)
    }
    
  }
  return (
    <>
      <section className="lesson">
        <h2>{lessonPlan.lessonTitle}</h2>

        <p>
          <strong>Grade:</strong> {lessonPlan.grade}
        </p>

        <p>
          <strong>Subject:</strong> {lessonPlan.subject}
        </p>

        <p>
          <strong>Topic:</strong> {lessonPlan.topic}
        </p>

        <h3>Objective</h3>
        <p>{lessonPlan.objective}</p>

        <h3>Activity</h3>
        <p>{lessonPlan.activity}</p>

        <h3>Discussion Questions</h3>
        <ul>
          {lessonPlan.discussionQuestions.map((question) => (
            <li key={question}>{question}</li>
          ))}
        </ul>

        <h3>Differentiation</h3>
        <p>
          <strong>Support:</strong> {lessonPlan.differentiation.support}
        </p>
        <p>
          <strong>Extension:</strong> {lessonPlan.differentiation.extension}
        </p>

        <h3>Assessment</h3>
        <p>{lessonPlan.assessment}</p>

        <small>Generated by: {lessonPlan.generatedBy}</small>
      </section>
      <button type="button" onClick={handleSave} disabled={saved || saving}>
        {saving ? "Saving..." : saved ? "Lesson Plan Saved" : "Save Lesson Plan"}
      </button>
    </>
  );
}
