import type { Lesson, SavedLesson } from "@ai-teacher/shared";
import { saveLesson } from "../api/lessonApi";
import { useState } from "react";

type LessonDisplayProps = {
  lesson: Lesson | SavedLesson | null;
  setError: (message: string) => void;
};

export default function LessonDisplay({
  lesson,
  setError,
}: LessonDisplayProps) {
  const [saved, setSaved] = useState<boolean>(false);
  const [saving, setSaving] = useState<boolean>(false);

  async function handleSave() {
    if (!lesson || "id" in lesson) {
      return;
    }

    setSaving(true);
    try {
      await saveLesson(lesson);
      setSaved(true);
    } catch (error) {
      setError(
        error instanceof Error
          ? error.message
          : "Unable to save the lesson. Please try again.",
      );
    } finally {
      setSaving(false);
    }
  }

  if (!lesson) {
    return (
      <div className="empty-page">
        <p>No lesson to view.</p>
        <p>Generate a new lesson or view your lesson history.</p>
      </div>
    );
  }

  return (
    <>
      <section className="lesson">
        <h2>{lesson.lessonTitle}</h2>

        <div className="lesson-meta">
          <div>
            <span>Grade</span>
            <strong>{lesson.grade}</strong>
          </div>

          <div>
            <span>Subject</span>
            <strong>{lesson.subject}</strong>
          </div>

          <div>
            <span>Topic</span>
            <strong>{lesson.topic}</strong>
          </div>
        </div>

        <div className="lesson-section">
          <h3>Objective</h3>
          <p>{lesson.objective}</p>
        </div>

        <div className="lesson-section">
          <h3>Activity</h3>
          <p>{lesson.activity}</p>
        </div>

        <div className="lesson-section">
          <h3>Discussion Questions</h3>
          <ul>
            {lesson.discussionQuestions.map(
              (question: string, index: number) => (
                <li key={index}>{question}</li>
              ),
            )}
          </ul>
        </div>

        <div className="lesson-section">
          <h3>Differentiation</h3>

          <div className="differentiation-grid">
            <div>
              <h4>Support: </h4>
              <p>{lesson.differentiation.support}</p>
            </div>

            <div>
              <h4>Extension: </h4>
              <p>{lesson.differentiation.extension}</p>
            </div>
          </div>
        </div>

        <div className="lesson-section">
          <h3>Assessment</h3>
          <p>{lesson.assessment}</p>
        </div>

        <footer className="lesson-footer">
          <small>Generated by: {lesson.generatedBy}</small>
          {"createdAt" in lesson && (
            <small>Saved: {new Date(lesson.createdAt).toLocaleString()}</small>
          )}
        </footer>
      </section>
      {!("id" in lesson) && (
        <button type="button" onClick={handleSave} disabled={saved || saving}>
          {saving ? "Saving..." : saved ? "Lesson saved" : "Save lesson "}
        </button>
      )}
    </>
  );
}
