import type { LessonPlan } from "@ai-teacher/shared";

type LessonPlanDisplayProps = {
  lessonPlan: LessonPlan;
};

export default function LessonPlanDisplay({
  lessonPlan,
}: LessonPlanDisplayProps) {
  return (
    <section className="lesson">
      <h2>{lessonPlan.lessonTitle}</h2>

      <p>
        <strong>Grade:</strong> {lessonPlan.grade}
      </p>

      <p>
        <strong>Subject:</strong> {lessonPlan.subject}
      </p>

      <p>
        <strong>Topic:</strong> {lessonPlan.topic}
      </p>

      <h3>Learning Goal</h3>
      <p>{lessonPlan.objective}</p>

      <h3>Activity</h3>
      <p>{lessonPlan.activity}</p>

      <h3>Discussion Questions</h3>
      <ul>
        {lessonPlan.discussionQuestions.map((question) => (
          <li key={question}>{question}</li>
        ))}
      </ul>

      <h3>Differentiation</h3>
      <p>
        <strong>Support:</strong> {lessonPlan.differentiation.support}
      </p>
      <p>
        <strong>Extension:</strong> {lessonPlan.differentiation.extension}
      </p>

      <h3>Assessment</h3>
      <p>{lessonPlan.assessment}</p>

      <small>Generated by: {lessonPlan.generatedBy}</small>
    </section>
  );
}
