import type { SavedLesson } from "@ai-teacher/shared";

type LessonDisplayProps = {
  lesson: SavedLesson | null;
};

export default function LessonDisplay({ lesson }: LessonDisplayProps) {
  if (!lesson) {
    return (
      <div className="empty-page">
        <p>No lesson to view.</p>
        <p>Generate a new lesson or view your lesson history.</p>
      </div>
    );
  }

  return (
    <>
      <section className="lesson">
        <h2>{lesson.lessonTitle}</h2>

        <div className="lesson-meta">
          <div>
            <span>Grade</span>
            <strong>{lesson.grade}</strong>
          </div>

          <div>
            <span>Subject</span>
            <strong>{lesson.subject}</strong>
          </div>

          <div>
            <span>Topic</span>
            <strong>{lesson.topic}</strong>
          </div>
        </div>

        <div className="lesson-section">
          <h3>Objective</h3>
          <p>{lesson.objective}</p>
        </div>

        <div className="lesson-section">
          <h3>Activity</h3>
          <p>{lesson.activity}</p>
        </div>

        <div className="lesson-section">
          <h3>Discussion Questions</h3>
          <ul>
            {lesson.discussionQuestions.map(
              (question: string, index: number) => (
                <li key={index}>{question}</li>
              ),
            )}
          </ul>
        </div>

        <div className="lesson-section">
          <h3>Differentiation</h3>

          <div className="differentiation-grid">
            <div>
              <h4>Support: </h4>
              <p>{lesson.differentiation.support}</p>
            </div>

            <div>
              <h4>Extension: </h4>
              <p>{lesson.differentiation.extension}</p>
            </div>
          </div>
        </div>

        <div className="lesson-section">
          <h3>Assessment</h3>
          <p>{lesson.assessment}</p>
        </div>

        <footer className="lesson-footer">
          <small>Generated by: {lesson.generatedBy}</small>

          <small>Saved: {new Date(lesson.createdAt).toLocaleString()}</small>
        </footer>
      </section>
    </>
  );
}
