import type { Lesson, SavedLesson } from "@ai-teacher/shared";
import { saveLesson } from "../api/lessonApi";
import { useState } from "react";

type LessonDisplayProps = {
  lesson: Lesson | SavedLesson | null;
  setError: (message: string) => void;
};

export default function LessonDisplay({
  lesson,
  setError,
}: LessonDisplayProps) {
  const [saved, setSaved] = useState<boolean>(false);
  const [saving, setSaving] = useState<boolean>(false);

  async function handleSave() {
    if (lesson) {
      setSaving(true);
      try {
        await saveLesson(lesson);
        setSaved(true);
        alert("Lesson  saved");
      } catch (error) {
        setError(`Unable to save the lesson. ${error}`);
      } finally {
        setSaving(false);
      }
    }
  }

  if (!lesson) {
    return null;
  }

  return (
    <>
      <section className="lesson">
        <h2>{lesson.lessonTitle}</h2>

        <p>
          <strong>Grade:</strong> {lesson.grade}
        </p>

        <p>
          <strong>Subject:</strong> {lesson.subject}
        </p>

        <p>
          <strong>Topic:</strong> {lesson.topic}
        </p>

        <h3>Objective</h3>
        <p>{lesson.objective}</p>

        <h3>Activity</h3>
        <p>{lesson.activity}</p>

        <h3>Discussion Questions</h3>
        <ul>
          {lesson.discussionQuestions.map((question: string) => (
            <li key={question}>{question}</li>
          ))}
        </ul>

        <h3>Differentiation</h3>
        <p>
          <strong>Support:</strong> {lesson.differentiation.support}
        </p>
        <p>
          <strong>Extension:</strong> {lesson.differentiation.extension}
        </p>

        <h3>Assessment</h3>
        <p>{lesson.assessment}</p>

        <small>Generated by: {lesson.generatedBy}</small>
        <br />
        {"createdAt" in lesson && (
          <small>Saved: {new Date(lesson.createdAt).toLocaleString()}</small>
        )}
      </section>
      {!("id" in lesson) && (
        <button type="button" onClick={handleSave} disabled={saved || saving}>
          {saving ? "Saving..." : saved ? "Lesson saved" : "Save lesson "}
        </button>
      )}
    </>
  );
}
